import Head from "next/head";
import styled from "styled-components";
import PhoneSS from "../../comps/PhoneSS";
import Header from "../../comps/Header";

const Main = styled.div`
  background: var(--black);
  color: white;
  display: flex;
  justify-content: center;
`;

const Center = styled.div`
  max-width: 960px;
  // border: 1px solid red;
`;

const screenshots = [
  {
    id: 5,
    img_url: "../screenshots/petsave/6.png",
  },
  //   {
  //     id: 2,
  //     img_url: "../screenshots/petsave/3.png",
  //   },
  //   {
  //     id: 3,
  //     img_url: "../screenshots/petsave/1.png",
  //   },
  {
    id: 4,
    img_url: "../screenshots/petsave/2.png",
  },
  {
    id: 1,
    img_url: "../screenshots/petsave/4.png",
  },
  {
    id: 6,
    img_url: "../screenshots/petsave/5.png",
  },
  {
    id: 7,
    img_url: "../screenshots/petsave/7.png",
  },
  {
    id: 8,
    img_url: "../screenshots/petsave/8.png",
  },
];

export default function Pantro() {
  return (
    <Main>
      <Head>
        <title>Projects | Petsave</title>
        <meta name="description" content="Generated by create next app" />
        <link href="" />
      </Head>
      <Center>
        <Header text="Petsave" />
        {screenshots.map((o) => {
          return <PhoneSS key={o.id} img_url={o.img_url} />;
        })}
      </Center>
    </Main>
  );
}
