import Head from "next/head";
import styled from "styled-components";
import Card from "../comps/Card";
import Icon from "../comps/Icon";
import Header from "../comps/Header";

// --gutterSpace: 32px;
// --screenXs: 576px;
// --screenXsMin: 575.98px;
// --screenSm: 768px;
// --screenSmMin: 767.98px;
// --screenMd: 1024px;
// --screenMdMin: 1023.98px;
// --screenLg: 1168px;
// --screenXl: 1472px;

const cards = [
  {
    title: "CRM",
    // description: "A CRM with ",
    img_url: "/placeholder.jpg",
  },
  {
    title: "Pantro",
    // description: "A Pantry app for your phone",
    img_url: "/pantro_thumb.png",
  },
  {
    title: "Petsave",
    description: "",
    img_url: "/petsave_thumb.png",
  },
  {
    title: "Poman",
    description: "",
    img_url: "/poman_thumb.png",
  },
  {
    title: "Get'em",
    description: "",
    img_url: "/getem_thumb.png",
  },
];

const icons = [
  {
    img_url: "icons/AWS.svg",
    tooltip: "AWS (DynamoDB, SES, SMS, S3)",
  },
  {
    img_url: "icons/React.svg",
    tooltip: "React",
  },
  {
    img_url: "icons/Javascript.svg",
    tooltip: "Javascript",
  },
  {
    img_url: "icons/PHP.svg",
    tooltip: "PHP",
  },
  {
    img_url: "icons/MySql.svg",
    tooltip: "MySql",
  },
  {
    img_url: "icons/PostgreSQL.svg",
    tooltip: "PostgreSQL",
  },
  {
    img_url: "icons/NextJS.svg",
    tooltip: "NextJS",
  },
  {
    img_url: "icons/NodeJS.svg",
    tooltip: "NodeJS",
  },
  {
    img_url: "icons/HTML.svg",
    tooltip: "HTML",
  },
  {
    img_url: "icons/CSS.svg",
    tooltip: "CSS: Cascaded Style Sheets",
  },
  {
    img_url: "icons/Adobe.svg",
    tooltip: "Adobe Creative Suite",
  },
  {
    img_url: "icons/Asana.svg",
    tooltip: "Asana",
  },
  {
    img_url: "icons/Figma.svg",
    tooltip: "Figma",
  },
  {
    img_url: "icons/Firebase.svg",
    tooltip: "Firebase",
  },
  {
    img_url: "icons/Material.svg",
    tooltip: "Material Design",
  },
  {
    img_url: "icons/Postman.svg",
    tooltip: "Postman",
  },
  {
    img_url: "icons/Python.svg",
    tooltip: "Python",
  },
  {
    img_url: "icons/Sass.svg",
    tooltip: "Sass: Syntactically Awesome Style Sheets",
  },
  {
    img_url: "icons/Wordpress.svg",
    tooltip: "Wordpress",
  },
];

const Main = styled.div`
  background: var(--black);
  color: white;
  display: flex;
  justify-content: center;
`;

const Center = styled.div`
  width: 60vw;
  border: 1px solid red;
`;

const Top = styled.div`
  // border: 1px solid red;
  height: 60vh;
`;

const Projects = styled.div`
  // border: 1px solid blue;
  height: 30vh;
  display: inline-flex;
`;

const Apps = styled.div`
  // border: 1px solid green;
  height: 10vh;
  display: flex;
`;

export default function Home() {

//add all adobe stuiff as icons
//creative tooltip
//animations when clicking arrows

  return (
    <Main>
      <Center>
        <Head>
          <title>Josh Renema</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/apple.svg" />
        </Head>
        <Top></Top>
        <Header text="Projects" />
        <Projects>
          {cards.map((o) => {
            return (
              <Card
                title={o.title}
                img_url={o.img_url}
                description={o.description}
              />
            );
          })}
        </Projects>
        <Header text="" />
        <Apps>
          {icons.map((o) => {
            return (
              <Icon 
                tooltip={o.tooltip}
                img_url={o.img_url}
              />
            );
          })}
        </Apps>
      </Center>
    </Main>
  );
}
