import Head from "next/head";
import styled from "styled-components";
import React, { useState } from "react";
import { Document, Page, pdfjs } from "react-pdf";
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
import Button from "../comps/Button.js";

const Main = styled.div`
  background: var(--black);
  color: white;
  display: flex;
  justify-content: center;
`;

const Download = styled.div`
  display: flex;
  flex-direction: center;
  align-items: center;
  // border: 1px solid red;
  margin: 20px 40.5%;
  *{
    display: flex;
    flex-direction: center;
    align-items: center;
  }
`;

const ResumeCont = styled.div`
  border-radius: 4px;
  border: 1px solid var(--secondary-bg);
`;

export default function Resume() {
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
  }

  return (
    <Main>
      <Head>
        <title>Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/logo.png" />
      </Head>
      <div>
        <Download>
          <a href="JoshRenema_Resume.pdf" download="JoshRenema_Resume">
            <Button text="Download Resume" width="100px" />
          </a>
        </Download>
        <ResumeCont>
          <Document file="josh_renema_resume.pdf" onLoadSuccess={onDocumentLoadSuccess}>
            <Page pageNumber={pageNumber} width={958} />
          </Document>
        </ResumeCont>
        <Download>
          <a href="josh_renema_resume.pdf" download="josh_renema_resume">
            <Button text="Download Resume" width="100px" />
          </a>
        </Download>
      </div>
    </Main>
  );
}
